// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoresRequest stores request
//
// swagger:model StoresRequest
type StoresRequest struct {

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// owner
	// Example: Syifa Prasetyo
	Owner string `json:"owner,omitempty"`

	// store address
	// Example: Banjaran, Kab. Bandung
	StoreAddress string `json:"store_address,omitempty"`

	// store id
	// Example: 1
	StoreID int64 `json:"store_id,omitempty"`

	// store name
	// Example: Warung Bersih
	StoreName string `json:"store_name,omitempty"`

	// store phone
	// Example: 088220138765
	StorePhone string `json:"store_phone,omitempty"`

	// store photo
	// Example: sp1.jpg
	StorePhoto string `json:"store_photo,omitempty"`
}

// Validate validates this stores request
func (m *StoresRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stores request based on context it is used
func (m *StoresRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoresRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoresRequest) UnmarshalBinary(b []byte) error {
	var res StoresRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
