// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Stores stores
//
// swagger:model Stores
type Stores struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// store name
	// Example: Warung Bersih
	StoreName string `json:"store_name,omitempty"`

	// store photo
	// Example: sp1.jpg
	StorePhoto string `json:"store_photo,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this stores
func (m *Stores) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stores based on context it is used
func (m *Stores) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Stores) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Stores) UnmarshalBinary(b []byte) error {
	var res Stores
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
